name: Package

# When a pull request is opened/reopened or when the head branch of the pull request is updated.
on:
  pull_request:


jobs:
  build-dependabot-pr:
    if: github.actor == 'dependabot[bot]'
    name: Package distribution file for a dependabot PR
    runs-on: ubuntu-latest
    steps:
      - name: Init a git repo
        uses: actions/checkout@v2
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Package
        run: |
          npm ci
          npm test
          npm run package
      - name: Commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git add dist/
          git commit -m "chore: Update dist" || echo "No changes to commit"
          git push
  build-contributor-pr:
    name: Check distribution file
    if: github.actor != 'dependabot[bot]' && github.event.commits[0].author.name != 'GitHub Actions'
    runs-on: ubuntu-latest
    steps:
      - name: Init a git repo
        uses: actions/checkout@v2
      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Package
        run: |
          npm ci
          npm test
          npm run package
      - name: Check git diff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git diff --exit-code dist/index.js