on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

name: Package

jobs:
  check:
    name: Package distribution file
    runs-on: ubuntu-latest
    steps:
    - name: Check out PR commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Package
      run: |
        npm ci
        npm test
        npm run package
    - name: Commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git add dist/
        git commit -m "chore: Update dist" || echo "No changes to commit"
        git push
